name: Teste 4 - Rota inexistente "/heroes"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run Jest test for Nonexistent Route
      run: npx jest -t 'Deve retornar erro 404 ao buscar uma rota inexistente "/heroes"'
