name: Teste Nave Millennium Falcon

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-nave-millennium-falcon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run Teste Nave Millennium Falcon
      run: npm test -- -t "Deve recuperar informações da nave Millennium Falcon"
